language: go
go: 1.x

sudo: false

before_install: go get github.com/mitchellh/gox
install: /bin/true

script:
  - go get -t -v ./...
  - gox -osarch="linux/arm" -verbose ./...

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: TyRPs0uQwaj54GA0MXg3RZKCDZSGKlbofrgsbdbGnTEtCclJeXfWf91d1Na9G6CoatsnVowYlLkUCFG6pv/0+xb42zLLJlbTKv3oedxG4xWvBmWw1PyHmtEdu3invvyk2Iqkm+Rj6OIZBJZ08kGqG9axYZ/uU2HXK/phfeNrta23DdPFem+fUFBYRNLSu5PYVB15q4KGBkDqaA0lvH8IyCMnIe2paTZZ6Jss5diPEtjpeq4GowNOYGYUsfGn82R6WgEgw6TXWRSCs80AB3thHhix5l+1VEatEqpat8ifk7qz0ZfI9ONK+dLah+91gFgsMQgcOLrfc/rYGEB2XyJfhNpIw5176tmpfz0bGImI/hzwpCKvvS1hMbGMF6cZkTwlIc7EIcO+GNhd/66mznT1KZ5kR5spQ03q3dGn8m/l+hqQt63tT6Pn3MGLj6DlXjfYRO2RhDbAgWE9SziQIC1avRT0ATFwu1qXOB5JwlyjTQBTi/bln5n3p3h3M3z4mX4EVAwEV1IiySH+Efe40++Xlgp8c9E5ZZTLnh2oqr3MRkVC24IKeHUnN4DS/M7JaU5whJJtZ0qf3xsYfRQvKSvmG4zeIQGw48zi5godz74TKq3Tc/X1NmLZFQX2aU9WsAXUCSE/kFzdyTUNhryYfeqIWp+r7POzIO0Wwzo5xxP2C/M=
  file: "./ruuvi2db_linux_arm"
  on:
    repo: s5i/ruuvi2db
    tags: true
