ui:
  provided_endpoints:
    ui: ":8000"

  consumed_endpoints:
    storage: "localhost:7800"

storage:
  provided_endpoints:
    data: "localhost:7800"
    admin: "localhost:7801"

  consumed_endpoints:
    reader: "localhost:7900"

  reader_consumer:
    query_period: "1m"
    max_staleness: "2m"
    mac_filter:
      - "AA:AA:AA:AA:AA:AA"
      - "BB:BB:BB:BB:BB:BB"

  database:
    bolt:
      path: "/appdata/ruuvi2db.db"
      retention_window: "8760h"
      allow_schema_update: false

reader:
  provided_endpoints:
    data: "localhost:7900"

  bluetooth:
    watchdog_timeout: "5m"

  data:
    max_staleness: "5m"
    mac_filter:
      - "AA:AA:AA:AA:AA:AA"
      - "BB:BB:BB:BB:BB:BB"
